spring.application.name=feedback

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/hsenid_feedback

# Server
server.port=8080

# Allow cross origin from Next.js
spring.web.cors.allowed-origins=http://localhost:3000